name: release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Kernel version'
        default: ''
        required: true
      arch:
        description: 'Kernel architecture'
        default: 'x86'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install github-release
      run: |
        sudo wget https://github.com/github-release/github-release/releases/download/v0.9.0/linux-amd64-github-release.bz2 -O /usr/local/bin/github-release.bz2
        sudo bunzip2 /usr/local/bin/github-release.bz2
        sudo chmod 0755 /usr/local/bin/github-release

    - name: Build kernel
      run: |
        git tag v${{ github.event.inputs.version }}-burmilla
        git checkout tags/v${{ github.event.inputs.version }}-burmilla -b v${{ github.event.inputs.version }}-burmilla
        KERNEL_TAG=${{ github.event.inputs.version }} OVERRIDE_KERNEL_ARCH=${{ github.event.inputs.arch }} make release

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Publish release
      run: ${PWD}/dist/publish.sh
      env:
        GITHUB_TOKEN: ${{ secrets.OS_KERNEL_RELEASE_TOKEN }}
